
-- =============================================
--  EXCELLENC SQL CAPSTONE PROJECT TEMPLATE
-- =============================================

-- SECTION 1: DATABASE CREATION
-- 1. Create a new database named: EdTechLearnPro
-- 2. Switch into the database. 

CREATE DATABASE EdTechLearnPro

USE EdTechLearnPro

-- SECTION 2: TABLE CREATION (DDL)
-- Write CREATE TABLE scripts here


CREATE TABLE STUDENTS
(
STUDENTID INT PRIMARY KEY,
FULLNAME VARCHAR(100),
EMAIL VARCHAR(100) NOT NULL UNIQUE,
PHONE VARCHAR(10) UNIQUE CHECK (LEN(PHONE) = 10 AND PHONE NOT LIKE '%[^0-9]%'),
CITY VARCHAR(100),
STATE VARCHAR(100),
REGISTRATIONDATE DATETIME,
ISACTIVE BIT DEFAULT 1
)


DROP TABLE STUDENTS
DROP TABLE COURSES
DROP TABLE ENROLLMENTS
DROP TABLE PAYMENTS
DROP TABLE TRAINERS
DROP TABLE TRAINER_COURSE_MAPPING
DROP TABLE MARKETING


CREATE TABLE COURSES
(
COURSEID VARCHAR(50) PRIMARY KEY,
COURSENAME VARCHAR(50) UNIQUE,
CATEGORY VARCHAR(100),
COURSEFEE INT,
DIFFICULTYLEVEL VARCHAR(100) CHECK(DIFFICULTYLEVEL IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')) DEFAULT 'BEGINNER'
)


CREATE TABLE ENROLLMENTS
(
ENROLLMENTID VARCHAR(50) PRIMARY KEY,
STUDENTID INT NOT NULL,
COURSEID VARCHAR(50) NOT NULL,
ENROLLMENTDATE DATE DEFAULT GETDATE(),
DISCOUNT DECIMAL(5,2) DEFAULT 0 CHECK(DISCOUNT >= 0 AND DISCOUNT <= 100),
PAYMENTSTATUS VARCHAR(50) CHECK(PAYMENTSTATUS IN ('PENDING','COMPLETED','FAILED')) DEFAULT 'PENDING',
FOREIGN KEY (STUDENTID)
REFERENCES STUDENTS(STUDENTID),
FOREIGN KEY (COURSEID)
REFERENCES COURSES(COURSEID)
)



CREATE TABLE PAYMENTS
(
PAYMENTID VARCHAR(100) PRIMARY KEY,
ENROLLMENTID VARCHAR(50) NOT NULL,
AMOUNTPAID DECIMAL(10,2) CHECK(AMOUNTPAID >= 0),
PAYMENTDATE DATETIME DEFAULT GETDATE(),
FOREIGN KEY (ENROLLMENTID)
REFERENCES ENROLLMENTS(ENROLLMENTID)
)


CREATE TABLE TRAINERS
(
TRAINERID INT PRIMARY KEY,
TRAINERNAME VARCHAR(100) NOT NULL,
EXPERTISE VARCHAR(100),
SATISFACTIONSCORE DECIMAL(3,2) CHECK(SATISFACTIONSCORE BETWEEN 0 AND 5)
)

CREATE TABLE TRAINER_COURSE_MAPPING
(
MAPPINGID INT PRIMARY KEY,
TRAINERID INT NOT NULL,
COURSEID VARCHAR(50) NOT NULL,
ASSIGNEDDATE DATETIME DEFAULT GETDATE(),
FOREIGN KEY(TRAINERID)
REFERENCES TRAINERS(TRAINERID),
FOREIGN KEY(COURSEID)
REFERENCES COURSES(COURSEID),
UNIQUE(TRAINERID, COURSEID)
)

CREATE TABLE MARKETING
(
MARKETINGID INT PRIMARY KEY,
MONTHYEAR VARCHAR(50) NOT NULL,
CHANNEL VARCHAR(50) CHECK(CHANNEL IN('INSTAGRAM','YOUTUBE','GOOGELADS','FACEBOOK')),
SPEND DECIMAL(10,2) CHECK(SPEND >= 0),
LEADSGENERATED INT CHECK(LEADSGENERATED >= 0)
);


-- SECTION 3: IMPORT DATA FROM EXCEL


SELECT * FROM STUDENTS

SELECT * FROM INFORMATION_SCHEMA.TABLES

INSERT INTO STUDENTS (STUDENTID, FULLNAME, EMAIL, PHONE, CITY, STATE, REGISTRATIONDATE, ISACTIVE)
SELECT STUDENTID, FULLNAME, EMAIL, PHONE, CITY, STATE, REGISTRATIONDATE, ISACTIVE FROM [STUDENTS$]


SELECT * FROM STUDENTS

DROP TABLE STUDENTS$


SELECT * FROM COURSES


INSERT INTO COURSES (COURSEID, COURSENAME, CATEGORY, COURSEFEE, DIFFICULTYLEVEL)
SELECT COURSEID, COURSENAME, CATEGORY, COURSEFEE, DIFFICULTYLEVEL FROM [COURSES$]



SELECT * FROM COURSES



INSERT INTO ENROLLMENTS (ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT, PAYMENTSTATUS)
SELECT ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT, PAYMENTSTATUS FROM [ENROLLMENTS$]

SELECT * FROM ENROLLMENTS
SELECT * FROM ENROLLMENTS$

SELECT DISTINCT PaymentStatus FROM Enrollments$

SELECT DEFINITION
FROM SYS.check_constraints
WHERE parent_object_id =
OBJECT_ID('ENROLLMENTS')

INSERT INTO ENROLLMENTS
(ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT, PAYMENTSTATUS)

SELECT ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT,
CASE WHEN PAYMENTSTATUS = 'PAID' THEN 'PAID'
WHEN PAYMENTSTATUS = 'UNPAID' THEN 'UNPAID'

ALTER TABLE ENROLLMENTS
DROP CONSTRAINT CK__ENROLLMEN__PAYME__70A8B9AE

ALTER TABLE ENROLLMENTS
ADD CONSTRAINT CK_PAYMENTSTATUS
CHECK (PAYMENTSTATUS IN 
('PAID', 'UNPAID', 'PARTIALLY PAID'));


INSERT INTO ENROLLMENTS
(ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT, PAYMENTSTATUS)
SELECT DISTINCT ENROLLMENTID, STUDENTID, COURSEID, ENROLLMENTDATE, DISCOUNT, PAYMENTSTATUS FROM Enrollments$

SELECT * FROM ENROLLMENTS

SELECT COUNT(*) FROM ENROLLMENTS

SELECT *
FROM ENROLLMENTS$ WHERE EnrollmentID = 2001

SELECT * FROM STUDENTS
SELECT * FROM COURSES
SELECT * FROM ENROLLMENTS

SELECT * FROM PAYMENTS$

INSERT INTO PAYMENTS
(PAYMENTID, ENROLLMENTID, AMOUNTPAID, PAYMENTDATE)
SELECT DISTINCT PAYMENTID, ENROLLMENTID, AMOUNTPAID, PAYMENTDATE FROM PAYMENTS$

SELECT * FROM PAYMENTS

SELECT * FROM TRAINERS$

INSERT INTO TRAINERS
(TRAINERID, TRAINERNAME, EXPERTISE, SATISFACTIONSCORE)
SELECT DISTINCT TRAINERID, TRAINERNAME, EXPERTISE, SATISFACTIONSCORE FROM TRAINERS$

SELECT * FROM TRAINERS

SELECT * FROM TRAINER_COURSE_MAPPING$

INSERT INTO TRAINER_COURSE_MAPPING
(MAPPINGID, TRAINERID, COURSEID, ASSIGNEDDATE)
SELECT DISTINCT MAPPINGID, TRAINERID, COURSEID, ASSIGNEDDATE FROM TRAINER_COURSE_MAPPING$

DROP TABLE TRAINER_COURSE_MAPPING$

SELECT * FROM TRAINER_COURSE_MAPPING
SELECT * FROM TRAINER_COURSE_MAPPING$

DELETE FROM TRAINER_COURSE_MAPPING$
WHERE TRAINERID IS NULL
OR COURSEID IS NULL

SELECT * FROM TRAINER_COURSE_MAPPING$

INSERT INTO TRAINER_COURSE_MAPPING
(MAPPINGID, TRAINERID, COURSEID, ASSIGNEDDATE)
SELECT DISTINCT MAPPINGID, TRAINERID, COURSEID, ASSIGNEDDATE FROM TRAINER_COURSE_MAPPING$


SELECT * FROM TRAINER_COURSE_MAPPING


SELECT * FROM MARKETING$

INSERT INTO MARKETING
(MARKETINGID, MONTHYEAR, CHANNEL, SPEND, LEADSGENERATED)
SELECT DISTINCT MARKETINGID, MONTHYEAR, CHANNEL, SPEND, LEADSGENERATED FROM MARKETING$

ALTER TABLE MARKETING$
ADD MARKETINGID INT IDENTITY(1,1)
PRIMARY KEY

ALTER TABLE MARKETING
DROP CONSTRAINT CK__MARKETING__CHANN__03BB8E22 

ALTER TABLE MARKETING 
ADD CONSTRAINT CK_MARKETING_CHANNEL
CHECK(CHANNEL IN 
('Google Ads','Meta Ads','YouTube','LinkedIn','Email','Influencers'));

INSERT INTO MARKETING
(MARKETINGID, MONTHYEAR, CHANNEL, SPEND, LEADSGENERATED)
SELECT DISTINCT MARKETINGID, MONTHYEAR, CHANNEL, SPEND, LEADSGENERATED FROM MARKETING$

SELECT * FROM MARKETING

SELECT COUNT(*) FROM STUDENTS;
SELECT COUNT(*) FROM COURSES;
SELECT COUNT(*) FROM ENROLLMENTS;
SELECT COUNT(*) FROM PAYMENTS;
SELECT COUNT(*) FROM MARKETING;

SELECT * FROM STUDENTS
SELECT * FROM COURSES
SELECT * FROM ENROLLMENTS
SELECT * FROM PAYMENTS
SELECT * FROM MARKETING
SELECT * FROM TRAINERS
SELECT * FROM TRAINER_COURSE_MAPPING


DROP TABLE Enrollments$
DROP TABLE Marketing$
DROP TABLE Trainers$
DROP TABLE Payments$
DROP TABLE TRAINER_COURSE_MAPPING$

-- SECTION 4: ANALYTICAL QUERIES (DQL)

-- 1. Top 5 cities by student enrollments. 

SELECT TOP 5
S.CITY,
COUNT(E.ENROLLMENTID) 
AS TOTAL_ENROLLMENTS
FROM STUDENTS S
JOIN ENROLLMENTS E
ON S.STUDENTID = E.STUDENTID
GROUP BY S.CITY
ORDER BY TOTAL_ENROLLMENTS DESC

-- 2. Students enrolled in more than 2 courses. 

SELECT STUDENTID,
COUNT (COURSEID) AS TOTALCOURSES
FROM ENROLLMENTS
GROUP BY STUDENTID
HAVING COUNT(COURSEID) > 2

-- 3. Students with no payment records. 
SELECT * FROM ENROLLMENTS
SELECT * FROM PAYMENTS

SELECT DISTINCT STUDENTID
FROM ENROLLMENTS
WHERE ENROLLMENTID NOT IN
(
SELECT ENROLLMENTID FROM PAYMENTS
)



-- 4. Highest revenue generating month.

SELECT TOP 1
    MONTH(PaymentDate) AS RevenueMonth,
    SUM(AmountPaid) AS TotalRevenue
FROM PAYMENTS
GROUP BY MONTH(PaymentDate)
ORDER BY TotalRevenue DESC

--5. Top 3 most popular courses. 


SELECT TOP 3 
COURSENAME AS POPULARCOURSES, COUNT(E.STUDENTID) AS TOTALSTUDENTS
FROM COURSES AS C
JOIN ENROLLMENTS AS E 
ON  C.COURSEID = E.COURSEID
GROUP BY COURSENAME
ORDER BY TOTALSTUDENTS DESC

SELECT * FROM ENROLLMENTS
SELECT * FROM COURSES

--6. Enrollments with discount above average discount. 


SELECT AVG(DISCOUNT) AS AVGDISCOUNT FROM ENROLLMENTS

SELECT ENROLLMENTID, DISCOUNT
FROM ENROLLMENTS
WHERE DISCOUNT > 15


--7. States with more than 10 paid enrollments. 

SELECT S.STATE, COUNT(E.ENROLLMENTID) 
AS TOTAL_PAID_ENROLLMENTS
FROM STUDENTS S
JOIN ENROLLMENTS E
ON S.STUDENTID = E.STUDENTID
WHERE E.PAYMENTSTATUS = 'PAID'
GROUP BY S.STATE
HAVING COUNT(E.ENROLLMENTID) > 10


-- PART 5 — JOINS (ALL TYPES)
--Write JOIN queries that combine:
--Students + Enrollments + Courses

-- Display student enrollment details along with the courses they enrolled in and their enrollment date

SELECT 
S.FULLNAME,
C.COURSENAME,
E.ENROLLMENTID,
E.ENROLLMENTDATE
FROM STUDENTS S
JOIN ENROLLMENTS E
ON S.STUDENTID = E.STUDENTID
JOIN COURSES C
ON E.COURSEID = C.COURSEID

-- DISPLAY ALL STUDENTS ALONG WITH THEIR ENROLLED COURSES, INCLUDING STUDENTS WHO HAVE NOT ENROLLED YET

SELECT
S.STUDENTID,
E.COURSEID,
E.ENROLLMENTID
FROM STUDENTS AS S
LEFT JOIN ENROLLMENTS AS E
ON S.STUDENTID = E.STUDENTID
LEFT JOIN COURSES AS C
ON E.COURSEID = C.COURSEID

--Courses + TrainerCourseMapping + Trainers 
 --Trainer performance with number of assigned courses

 SELECT * FROM COURSES
 SELECT * FROM TRAINER_COURSE_MAPPING
 SELECT * FROM TRAINERS


 SELECT 
 T.TRAINERNAME,
 COUNT(M.COURSEID) AS TOTAL_ASSIGNED_COURSES
 FROM COURSES C
 RIGHT JOIN TRAINER_COURSE_MAPPING M
 ON C.COURSEID = M.COURSEID
 RIGHT JOIN TRAINERS T
 ON M.TRAINERID = T.TRAINERID
 GROUP BY T.TRAINERNAME

 -- Enrollments + Payments

 SELECT E.COURSEID,
 COUNT(E.ENROLLMENTID) AS
 TOTAL_ENROLLMENTS,
 SUM(P.AMOUNTPAID) AS TOTAL_REVENUE
 FROM ENROLLMENTS E
 INNER JOIN PAYMENTS P
 ON E.ENROLLMENTID = P.ENROLLMENTID
 GROUP BY E.COURSEID
 ORDER BY TOTAL_REVENUE DESC


 -- REVENUE PER COURSE

 SELECT 
 E.COURSEID,
 SUM(P.AMOUNTPAID) AS TOTAL_REVENUE
 FROM ENROLLMENTS AS E
 LEFT JOIN PAYMENTS AS P
 ON E.ENROLLMENTID = P.ENROLLMENTID
 GROUP BY E.COURSEID

 -- DISPLAY DISCOUNT FOR EACH COURSE WITH PAYMENT AMOUNT

 SELECT
 E.COURSEID, SUM(E.DISCOUNT) AS TOTAL_DISCOUNT, SUM(P.AMOUNTPAID) AS TOTAL_AMOUNT
 FROM ENROLLMENTS AS E
 LEFT JOIN PAYMENTS AS P
 ON E.ENROLLMENTID = P.ENROLLMENTID
 GROUP BY E.COURSEID
 ORDER BY E.COURSEID ASC

 -- Marketing + Enrollments (month based) 
 SELECT * FROM MARKETING
 SELECT * FROM ENROLLMENTS
 SELECT
    M.MONTHYEAR,
    M.CHANNEL,
    M.LEADSGENERATED,
    COUNT(E.ENROLLMENTID) AS TOTAL_ENROLLMENTS,
    M.SPEND,
    ROUND(
        COUNT(E.ENROLLMENTID) * 100.0 /
        NULLIF(M.LEADSGENERATED,0),2
    ) AS CONVERSION_RATE
FROM MARKETING M
LEFT JOIN ENROLLMENTS E
    ON FORMAT(E.ENROLLMENTDATE,'yyyy-MM') = M.MONTHYEAR
GROUP BY
    M.MONTHYEAR,
    M.CHANNEL,
    M.LEADSGENERATED,
    M.SPEND
ORDER BY
    M.MONTHYEAR
 

 --MONTHWISE REVENUE 
 --Display channel-wise marketing performance with enrollments

 SELECT M.MONTHYEAR, COUNT(E.ENROLLMENTID) AS TOTAL_ENROLLMENTS, M.CHANNEL, M.LEADSGENERATED, M.SPEND
 FROM MARKETING  AS M
 LEFT JOIN ENROLLMENTS AS E
 ON FORMAT(E.ENROLLMENTDATE, 'yyyy-MM') = M.MONTHYEAR
 GROUP BY M.MONTHYEAR, M.CHANNEL, M.LEADSGENERATED, M.SPEND
 ORDER BY M.MONTHYEAR




 -- City wise + course wise revenue summary

 SELECT * FROM STUDENTS
 SELECT * FROM COURSES
 SELECT * FROM ENROLLMENTS
 SELECT * FROM PAYMENTS

 SELECT S.CITY, C.COURSENAME, SUM(P.AMOUNTPAID) AS REVENUE
 FROM STUDENTS AS S
 JOIN ENROLLMENTS AS E
 ON S.STUDENTID = E.STUDENTID
 JOIN COURSES AS C
 ON E.COURSEID = C.COURSEID
 JOIN PAYMENTS AS P
 ON E.ENROLLMENTID = P.ENROLLMENTID
 GROUP BY S.CITY, C.COURSENAME
 ORDER BY S.CITY, REVENUE DESC


 --Student Name + Course Name + Trainer Name

 
SELECT S.FULLNAME, C.COURSENAME, T.TRAINERNAME
FROM STUDENTS S
JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
JOIN COURSES C ON E.COURSEID = C.COURSEID
JOIN TRAINER_COURSE_MAPPING M ON C.COURSEID = M.COURSEID
JOIN TRAINERS T ON M.TRAINERID = T.TRAINERID


--PART 6 — GROUP BY + HAVING + AGGREGATION
--- Monthly revenue

SELECT * FROM PAYMENTS

SELECT SUM(AMOUNTPAID) AS TOTAL_REVENUE, MONTH(PAYMENTDATE) AS MONTH
FROM PAYMENTS
GROUP BY MONTH(PAYMENTDATE)
HAVING SUM(AMOUNTPAID) > 0
ORDER BY MONTH(PAYMENTDATE)

--- Enrollment counts per course 
SELECT * FROM ENROLLMENTS

SELECT COUNT(ENROLLMENTID) AS ENROLLMENTS, COURSEID
FROM ENROLLMENTS
GROUP BY COURSEID
HAVING COUNT(ENROLLMENTID) > 0
ORDER BY COURSEID ASC

-- Average fee per category 

SELECT * FROM COURSES

SELECT AVG(COURSEFEE) AS AVGCOURSE_FEE, CATEGORY
FROM COURSES
GROUP BY CATEGORY
HAVING AVG(COURSEFEE) > 1000
ORDER BY CATEGORY 

-- Trainer satisfaction averages 
SELECT * FROM TRAINERS

SELECT CAST(ROUND(AVG(SATISFACTIONSCORE),2) AS DECIMAL(10,2)) AS AVGSATISFACTIONSCORE, EXPERTISE, TRAINERNAME
FROM TRAINERS 
GROUP BY TRAINERNAME, EXPERTISE
HAVING ROUND(AVG(SATISFACTIONSCORE),2) > 1
ORDER BY TRAINERNAME ASC

--State wise registration patterns 

SELECT * FROM STUDENTS

SELECT STATE, COUNT(STUDENTID) AS TOTALREGISTRATIONS
FROM STUDENTS
GROUP BY STATE
ORDER BY TOTALREGISTRATIONS DESC

--PART 7 — SUBQUERIES + CTEs 

-- Courses with above average enrollments

SELECT COURSEID, COUNT(ENROLLMENTID) AS TOTAL_ENROLLMENTS
FROM ENROLLMENTS
GROUP BY COURSEID
HAVING COUNT(ENROLLMENTID) >
(
    SELECT AVG(TOTAL_COUNT)
    FROM
    (
        SELECT COUNT(ENROLLMENTID) AS TOTAL_COUNT
        FROM ENROLLMENTS
        GROUP BY COURSEID
    ) AS COURSE_COUNTS
)


-- Students enrolled in the most expensive course

SELECT STUDENTID, COURSEID
FROM ENROLLMENTS
WHERE COURSEID IN
(
    SELECT COURSEID
    FROM COURSES
    WHERE COURSEFEE =
    (
        SELECT MAX(COURSEFEE)
        FROM COURSES
    )
)

-- Highest discount enrollment details

SELECT *
FROM ENROLLMENTS
WHERE DISCOUNT =
(
    SELECT MAX(DISCOUNT)
    FROM ENROLLMENTS
)


-- Revenue trend for last 6 months using CTE

WITH REVENUE_CTE AS
(
    SELECT
    MONTH(PAYMENTDATE) AS MONTH_NUMBER,
    SUM(AMOUNTPAID) AS TOTAL_REVENUE
    FROM PAYMENTS
    GROUP BY MONTH(PAYMENTDATE)
)

SELECT *
FROM REVENUE_CTE
ORDER BY MONTH_NUMBER DESC

-- PART 8 — WINDOW FUNCTIONS 
--- RANK() revenue per month 

SELECT
MONTH(PAYMENTDATE) AS MONTH_NUMBER,
SUM(AMOUNTPAID) AS TOTAL_REVENUE,

RANK() OVER
(
    ORDER BY SUM(AMOUNTPAID) DESC
) AS REVENUE_RANK

FROM PAYMENTS

GROUP BY MONTH(PAYMENTDATE)

-- DENSE_RANK() — Top 3 courses per month

SELECT
MONTH(P.PAYMENTDATE) AS MONTH_NUMBER,
E.COURSEID,
SUM(P.AMOUNTPAID) AS TOTAL_REVENUE,

DENSE_RANK() OVER
(
    PARTITION BY MONTH(P.PAYMENTDATE)

    ORDER BY SUM(P.AMOUNTPAID) DESC
) AS COURSE_RANK

FROM PAYMENTS P

INNER JOIN ENROLLMENTS E
ON P.ENROLLMENTID = E.ENROLLMENTID

GROUP BY
MONTH(P.PAYMENTDATE),
E.COURSEID

-- LAG() — Month-over-month revenue change
-- Compare current month revenue with previous month

SELECT
MONTH(PAYMENTDATE) AS MONTH_NUMBER,

SUM(AMOUNTPAID) AS CURRENT_MONTH_REVENUE,

LAG(SUM(AMOUNTPAID))
OVER
(
    ORDER BY MONTH(PAYMENTDATE)
) AS PREVIOUS_MONTH_REVENUE

FROM PAYMENTS

GROUP BY MONTH(PAYMENTDATE)

-- LEAD() to forecast next month trend
SELECT
MONTH(PAYMENTDATE) AS MONTH_NUMBER,

SUM(AMOUNTPAID) AS CURRENT_MONTH_REVENUE,

LEAD(SUM(AMOUNTPAID))
OVER
(
    ORDER BY MONTH(PAYMENTDATE)
) AS NEXT_MONTH_REVENUE

FROM PAYMENTS

GROUP BY MONTH(PAYMENTDATE)

--ROW_NUMBER() — Duplicate detection
-- Detect duplicate enrollments

SELECT

STUDENTID,
COURSEID,

ROW_NUMBER() OVER
(
    PARTITION BY STUDENTID, COURSEID

    ORDER BY STUDENTID
) AS ROW_NUM

FROM ENROLLMENTS


--PART 9 — VIEWS 
--vw_MonthlyRevenue 

-- Create monthly revenue view

CREATE VIEW vw_MonthlyRevenue AS

SELECT

MONTH(PAYMENTDATE) AS MONTH_NUMBER,

SUM(AMOUNTPAID) AS TOTAL_REVENUE,

COUNT(PAYMENTID) AS TOTAL_PAYMENTS

FROM PAYMENTS

GROUP BY MONTH(PAYMENTDATE)

SELECT *
FROM vw_MonthlyRevenue


-- Create trainer performance view

CREATE VIEW vw_TrainerPerformance AS

SELECT

T.TRAINERNAME,

T.EXPERTISE,

COUNT(TCM.COURSEID) AS TOTAL_ASSIGNED_COURSES,

ROUND(AVG(T.SATISFACTIONSCORE),2) AS AVG_SATISFACTION

FROM TRAINERS T

LEFT JOIN TRAINER_COURSE_MAPPING TCM
ON T.TRAINERID = TCM.TRAINERID

GROUP BY
T.TRAINERNAME,
T.EXPERTISE

SELECT *
FROM vw_TrainerPerformance


-- PART 10 — INDEXES
-- Create:
-- Index on Students.Email
-- Index on Courses.CourseName
-- Index on Enrollments.EnrollmentDate
-- Composite index (StudentID, CourseID)


-- Index on Students.EmaiL

CREATE INDEX IDX_STUDENTS_EMAIL
ON STUDENTS(EMAIL)
--This index helps when searching students using email.

--Example
SELECT *
FROM STUDENTS
WHERE EMAIL = 'student1@example.com'
--Instead of scanning the entire STUDENTS table, SQL directly locates the required email.



-- Index on Courses.CourseName

CREATE INDEX IDX_COURSES_COURSENAME
ON COURSES(COURSENAME)
--Useful when searching courses by name.

--Example

SELECT *
FROM COURSES
WHERE COURSENAME LIKE '%Python%'
--SQL can find the course much faster.


---- Index on Enrollments.EnrollmentDate

CREATE INDEX IDX_ENROLLMENTS_DATE
ON ENROLLMENTS(ENROLLMENTDATE)
--Useful for date filtering and reports.

--Example
SELECT *
FROM ENROLLMENTS
WHERE ENROLLMENTDATE
BETWEEN '2025-01-01' AND '2025-03-31'
--SQL quickly locates rows within the date range.

-- Composite Index

CREATE INDEX IDX_STUDENT_COURSE
ON ENROLLMENTS(STUDENTID, COURSEID)
--A composite index improves query performance by allowing SQL Server to quickly locate records when both StudentID and CourseID are used together in searches, filters, or joins.
 
--Example
SELECT *
FROM ENROLLMENTS
WHERE STUDENTID = 1001
AND COURSEID = 501


--PART 11 — STORED PROCEDURES
--Create procedures for:
--1. Fetching monthly revenue (IN parameter)

CREATE PROCEDURE sp_MonthlyRevenue
    @Month INT
AS
BEGIN

    SELECT
        MONTH(PaymentDate) AS MonthNo,
        SUM(AmountPaid) AS TotalRevenue
    FROM Payments
    WHERE MONTH(PaymentDate) = @Month
    GROUP BY MONTH(PaymentDate)

END


EXEC sp_MonthlyRevenue 5



--2. Adding a new student with validation (INOUT) 

CREATE PROCEDURE sp_AddStudent
(
    @StudentID INT,
    @FullName VARCHAR(100),
    @Email VARCHAR(100),
    @Phone VARCHAR(20),
    @City VARCHAR(50),
    @State VARCHAR(50),
    @Message VARCHAR(100) OUTPUT
)
AS
BEGIN

    IF EXISTS
    (
        SELECT *
        FROM Students
        WHERE Email = @Email
    )

    BEGIN
        SET @Message='Email already exists'
    END

    ELSE

    BEGIN

        INSERT INTO Students
        (
            StudentID,
            FullName,
            Email,
            Phone,
            City,
            State
        )

        VALUES
        (
            @StudentID,
            @FullName,
            @Email,
            @Phone,
            @City,
            @State
        )

        SET @Message='Student Added Successfully'

    END

END



DECLARE @Result VARCHAR(100)

EXEC sp_AddStudent
10000,
'Rithika',
'rithika@gmail.com',
'9876543210',
'Hyderabad',
'Telangana',
@Result OUTPUT

SELECT @Result

--3.Getting trainer performance above a threshold (OUT) 

CREATE PROCEDURE sp_TrainerPerformance
(
    @Threshold DECIMAL(4,2),
    @TotalTrainers INT OUTPUT
)
AS
BEGIN

    SELECT
        @TotalTrainers = COUNT(*)
    FROM Trainers
    WHERE SatisfactionScore > @Threshold

END

DECLARE @Count INT

EXEC sp_TrainerPerformance
4.0,
@Count OUTPUT

SELECT @Count AS TrainersAboveThreshold


--PART 12 — USER DEFINED FUNCTIONS
--Create:
--1. Scalar Function → fn_NetFeeAfterDiscount 

CREATE FUNCTION fn_NetFeeAfterDiscount
(
    @CourseFee DECIMAL(10,2),
    @Discount DECIMAL(10,2)
)

RETURNS DECIMAL(10,2)

AS
BEGIN

    DECLARE @NetFee DECIMAL(10,2)

    SET @NetFee =
    @CourseFee - (@CourseFee * @Discount / 100)

    RETURN @NetFee

END


SELECT dbo.fn_NetFeeAfterDiscount
(
50000,
10
)
AS NET_FEE


--2. Table Valued Function → return enrollments by course 
CREATE FUNCTION fn_EnrollmentsByCourse
(
    @CourseID INT
)

RETURNS TABLE

AS

RETURN

(
    SELECT
    ENROLLMENTID,
    STUDENTID,
    COURSEID,
    ENROLLMENTDATE

    FROM ENROLLMENTS

    WHERE COURSEID = @CourseID
)


SELECT *
FROM dbo.fn_EnrollmentsByCourse(501)


--PART 13 — EXCEPTION HANDLING
--Use TRY…CATCH inside stored procedures:
--Log errors into ErrorLog table
--Insert user friendly error messages 

--Step 1: Create ErrorLog Table
CREATE TABLE ERRORLOG
(
    ERRORID INT IDENTITY(1,1) PRIMARY KEY,
    ERRORMESSAGE VARCHAR(500),
    ERRORDATE DATETIME DEFAULT GETDATE()
)

--Whenever an error occurs, the error message gets stored here.

--Step 2: Stored Procedure with TRY...CATCH
CREATE PROCEDURE SP_MONTHLYREVENUE_ERRORHANDLING

    @MONTH INT

AS
BEGIN

    BEGIN TRY

        IF @MONTH < 1 OR @MONTH > 12
            THROW 50001, 'Invalid month entered.', 1;

        SELECT
            SUM(AMOUNTPAID) AS TOTAL_REVENUE
        FROM PAYMENTS
        WHERE MONTH(PAYMENTDATE) = @MONTH;

    END TRY

    BEGIN CATCH

        INSERT INTO ERRORLOG
        (
            ERRORMESSAGE
        )
        VALUES
        (
            ERROR_MESSAGE()
        );

        PRINT 'Revenue could not be calculated.';

    END CATCH

END

EXEC SP_MONTHLYREVENUE_ERRORHANDLING 1

EXEC SP_MONTHLYREVENUE_ERRORHANDLING 15


--checking errorlog

SELECT *
FROM ERRORLOG


--PART 14 — TRIGGERS
--Create:
--1. BEFORE INSERT → prevent discount > 50% 

CREATE TABLE AUDITLOG
(
    AUDITID INT IDENTITY(1,1) PRIMARY KEY,
    ENROLLMENTID INT,
    OLDDISCOUNT DECIMAL(10,2),
    NEWDISCOUNT DECIMAL(10,2),
    CHANGEDATE DATETIME DEFAULT GETDATE()
)

CREATE TRIGGER TRG_PREVENT_HIGH_DISCOUNT
ON ENROLLMENTS
AFTER INSERT
AS
BEGIN

    IF EXISTS
    (
        SELECT *
        FROM INSERTED
        WHERE DISCOUNT > 50
    )

    BEGIN

        RAISERROR
        (
            'Discount cannot exceed 50 percent',
            16,
            1
        )

        ROLLBACK TRANSACTION

    END

END



INSERT INTO ENROLLMENTS
(
    ENROLLMENTID,
    STUDENTID,
    COURSEID,
    ENROLLMENTDATE,
    DISCOUNT,
    PAYMENTSTATUS
)

VALUES
(
    9992,
    1001,
    501,
    GETDATE(),
    20,
    'Paid'
)

SELECT *
FROM ENROLLMENTS
WHERE ENROLLMENTID = 9992

-- Trigger prevents insertion when discount exceeds 50%.
-- If discount > 50, transaction is rolled back.

CREATE TRIGGER TRG_UNPAID_PAYMENT

ON ENROLLMENTS

AFTER INSERT

AS
BEGIN

    INSERT INTO PAYMENTS
    (
        PAYMENTID,
        ENROLLMENTID,
        AMOUNTPAID,
        PAYMENTDATE
    )

    SELECT
        (SELECT ISNULL(MAX(PAYMENTID),3000) + 1 FROM PAYMENTS),
        ENROLLMENTID,
        0,
        GETDATE()

    FROM INSERTED

    WHERE PAYMENTSTATUS = 'Unpaid'

END

INSERT INTO ENROLLMENTS
(
    ENROLLMENTID,
    STUDENTID,
    COURSEID,
    ENROLLMENTDATE,
    DISCOUNT,
    PAYMENTSTATUS
)

VALUES
(
    9996,
    1001,
    501,
    GETDATE(),
    10,
    'Unpaid'
)

SELECT *
FROM PAYMENTS
WHERE ENROLLMENTID = 9996


--3. AFTER UPDATE → log old + new values into AuditLog table 

CREATE TRIGGER TRG_AUDIT_UPDATE

ON ENROLLMENTS

AFTER UPDATE

AS
BEGIN
INSERT INTO AUDITLOG
(
    ENROLLMENTID,
    OLDDISCOUNT,
    NEWDISCOUNT,
    CHANGEDATE
)
    SELECT
        D.ENROLLMENTID,
        D.DISCOUNT,
        I.DISCOUNT,
        GETDATE()

    FROM DELETED D

    INNER JOIN INSERTED I
    ON D.ENROLLMENTID = I.ENROLLMENTID

END


UPDATE ENROLLMENTS
SET DISCOUNT = 25
WHERE ENROLLMENTID = 2001

SELECT *
FROM AUDITLOG


--PART 15 — FINAL ANALYTICAL TASKS
--Produce SQL results for:
--CAC (Cost per Acquisition)- ROI per marketing channel

SELECT
    M.CHANNEL,
    SUM(M.SPEND) AS TOTAL_SPEND,
    COUNT(E.ENROLLMENTID) AS TOTAL_ENROLLMENTS,
    SUM(M.SPEND) / COUNT(E.ENROLLMENTID) AS CAC

FROM MARKETING M

LEFT JOIN ENROLLMENTS E
ON FORMAT(E.ENROLLMENTDATE,'yyyy-MM') = M.MONTHYEAR

GROUP BY M.CHANNEL

HAVING COUNT(E.ENROLLMENTID) > 0

ORDER BY CAC

--- 12 month enrollment heatmap (Month × City) 

SELECT
    FORMAT(E.ENROLLMENTDATE,'yyyy-MM') AS MONTHYEAR,
    S.CITY,
    COUNT(E.ENROLLMENTID) AS TOTAL_ENROLLMENTS

FROM ENROLLMENTS E

INNER JOIN STUDENTS S
ON E.STUDENTID = S.STUDENTID

GROUP BY
FORMAT(E.ENROLLMENTDATE,'yyyy-MM'),
S.CITY

ORDER BY
MONTHYEAR,
TOTAL_ENROLLMENTS DESC

--- Top course & worst course by revenue 
SELECT
    TOP 1
    E.COURSEID,
    SUM(P.AMOUNTPAID) AS TOTAL_REVENUE

FROM ENROLLMENTS E

INNER JOIN PAYMENTS P
ON E.ENROLLMENTID = P.ENROLLMENTID

GROUP BY E.COURSEID

ORDER BY TOTAL_REVENUE DESC


--Lowest revenue Course
SELECT
    TOP 1
    E.COURSEID,
    SUM(P.AMOUNTPAID) AS TOTAL_REVENUE

FROM ENROLLMENTS E

INNER JOIN PAYMENTS P
ON E.ENROLLMENTID = P.ENROLLMENTID

GROUP BY E.COURSEID

ORDER BY TOTAL_REVENUE ASC

--- Trainer impact on course satisfaction 

SELECT
    T.TRAINERNAME,
    T.EXPERTISE,
    CAST(AVG(T.SATISFACTIONSCORE) AS DECIMAL(10,2))
        AS AVG_SATISFACTION

FROM TRAINERS T

GROUP BY
T.TRAINERNAME,
T.EXPERTISE

ORDER BY AVG_SATISFACTION DESC

--- Month over month business growth 

SELECT
    MONTH(PAYMENTDATE) AS MONTHNO,

    SUM(AMOUNTPAID) AS REVENUE,

    LAG(SUM(AMOUNTPAID))
    OVER(ORDER BY MONTH(PAYMENTDATE))
    AS PREVIOUS_MONTH_REVENUE

FROM PAYMENTS

GROUP BY MONTH(PAYMENTDATE)

ORDER BY MONTHNO







